### ISSUE TITLE
[Threshold] Remake into multi-level threshold

### ISSUE THREAD

**Issue by eigenein** [eigenein/my-iot-rs#148]
Add a loggable `level` sensor.

Example configuration:

```toml
[services.threshold]
levels = [1.0, 2.0, 3.0]
gray_zone_width = 0.1
```
